# Fetching Data from an API and then creating a dataset

In [1]:
import pandas as pd
import requests

In [9]:
url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYmZjMjhjZGZiYmFhNzBkZjM4NmZkMDk5Y2Q0YjZiMSIsIm5iZiI6MTc5MTc4ODUzOC4yNCwic3ViIjoiNmFjYzg1ZmFjMGZhYTRmODBiYjdiY2JlIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.uzPNtywkob8OS6LXuFA5-ac4FtgrqQVqyWwLgPPnrdU"
}

response = requests.get(url, headers=headers)

In [10]:
df = pd.DataFrame(response.json()['results'])[['id', 'title', 'release_date', 'overview', 'popularity', 'vote_average', 'vote_count']]

In [11]:
df.head()

,id,title,release_date,overview,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,2026-06-23,"Arkham Asylum has been destroyed, and all its ...",45.5457,9.117,446
1,980431,Avatar Aang: The Last Airbender,2026-07-24,"Avatar Aang, the world's last Airbender, learn...",76.5399,9.103,1304
2,1007757,Swapped,2026-05-01,"A small woodland creature and a majestic bird,...",49.2355,8.863,2236
3,1632181,Accidental Partners,2026-03-12,Two women discover they were both scammed by t...,15.4531,8.838,395
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,The Demon Slayer Corps are drawn into the Infi...,59.4823,8.801,2269

In [12]:
df.shape

(20, 7)

In [19]:
# # Fetch all the data by making the request using a loop
# for i in range(1,567):
#     # update the page in the url with the 'i'
#     url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"

#     headers = {
#     "accept": "application/json",
#     "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYmZjMjhjZGZiYmFhNzBkZjM4NmZkMDk5Y2Q0YjZiMSIsIm5iZiI6MTc5MTc4ODUzOC4yNCwic3ViIjoiNmFjYzg1ZmFjMGZhYTRmODBiYjdiY2JlIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.uzPNtywkob8OS6LXuFA5-ac4FtgrqQVqyWwLgPPnrdU"
#     }

#     response = requests.get(url=url, headers=headers)
#     temp_df = pd.DataFrame(response.json()['results'])[['id','title', 'release_date', 'overview', 'popularity', 'vote_average', 'vote_count']]
#     df = pd.concat([df, temp_df], ignore_index=True)

In [22]:
import pandas as pd
import requests
import time

In [27]:
# initialize empty list to collect DataFrames
df_list = []

# Use Session object to reuse the same TCP connection (faster and more stable)
with requests.Session() as session:
    
    headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYmZjMjhjZGZiYmFhNzBkZjM4NmZkMDk5Y2Q0YjZiMSIsIm5iZiI6MTc5MTc4ODUzOC4yNCwic3ViIjoiNmFjYzg1ZmFjMGZhYTRmODBiYjdiY2JlIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.uzPNtywkob8OS6LXuFA5-ac4FtgrqQVqyWwLgPPnrdU"
    }
    
    session.headers.update(headers)

    for i in range(1,501):
        # update the page in the url with the 'i'
        url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"

        try:
            response = session.get(url=url)

            # check if request was successful
            if response.status_code == 200:
                data = response.json().get('results',[])
                if data:
                    temp_df = pd.DataFrame(data)[['id','title', 'release_date', 'overview', 'popularity', 'vote_average', 'vote_count']]
                    df_list.append(temp_df)
            else:
                print(f"Failed to fetch page {i}. Status code: {response.status_code}")
        except (requests.exceptions.RequestException, ConnectionError) as e:
            print(f"Connection error on page {i}: {e}. Retrying in 5 seconds...")
            time.sleep(5)
            continue

        time.sleep(0.3)

if df_list:
    df_new = pd.concat(df_list, ignore_index=True)
else:
    df_new = pd.DataFrame()

In [31]:
df_new.shape

(10000, 7)

In [30]:
df_new

,id,title,release_date,overview,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,2026-06-23,"Arkham Asylum has been destroyed, and all its ...",45.5457,9.117,446
1,980431,Avatar Aang: The Last Airbender,2026-07-24,"Avatar Aang, the world's last Airbender, learn...",76.5399,9.103,1304
2,1007757,Swapped,2026-05-01,"A small woodland creature and a majestic bird,...",49.2355,8.863,2236
3,1632181,Accidental Partners,2026-03-12,Two women discover they were both scammed by t...,15.4531,8.838,395
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,The Demon Slayer Corps are drawn into the Infi...,59.4823,8.801,2269
...,...,...,...,...,...,...,...
9995,10823,Children of the Corn,1984-03-09,A traveling couple end up in an abandoned Nebr...,8.1641,5.716,1185
9996,8860,Metro,1997-01-16,"Roper, a hostage negotiator catches a murderou...",3.5258,5.700,634
9997,17941,Hush,1998-03-06,Jackson and Helen are in love and about to hav...,3.1891,5.717,331
9998,11472,Nine Months,1995-07-12,When he finds out his longtime girlfriend is p...,6.3271,5.717,728
9999,844417,Marlowe,2023-02-15,Private detective Philip Marlowe becomes embro...,6.6967,5.716,449

In [32]:
df_new.to_csv('movies.csv')